# Generated by Django 5.2.5 on 2025-08-31 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payments"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payments",
        ),
    ]
