# Generated by Django 5.2.5 on 2025-08-11 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название курса', max_length=100, verbose_name='Название курса')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='online_learning/photo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название урока', max_length=100, verbose_name='Название урока')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='online_learning/photo', verbose_name='Фото')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('course', models.ForeignKey(blank=True, help_text='Название урока', null=True, on_delete=django.db.models.deletion.SET_NULL, to='online_learning.course', verbose_name='Название урока')),
            ],
        ),
    ]
